// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVoXmI75f8kNO8_K0U6M02tMg7FeAiNQ',
    appId: '1:139807452994:android:5a80c0067d4a6b6f9f22db',
    messagingSenderId: '139807452994',
    projectId: 'soowgoodapp',
    storageBucket: 'soowgoodapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusUnXAq7nLZN1htvtkeLyU-6CcppALSs',
    appId: '1:139807452994:ios:5dc42cf0fdd2a31e9f22db',
    messagingSenderId: '139807452994',
    projectId: 'soowgoodapp',
    storageBucket: 'soowgoodapp.appspot.com',
    androidClientId: '139807452994-qcd941oajkf7bm8bhqnf008use54f20v.apps.googleusercontent.com',
    iosClientId: '139807452994-7ljbs36rs46q2b2iitc07bog8ott345p.apps.googleusercontent.com',
    iosBundleId: 'com.app.soowgood',
  );
}
